# Python Experiment 2

#### ==========================================================================
#### Name: **Cruz, Kathryn Angel S.**
#### Section: **2ECE-A**
#### ==========================================================================

### **PROBLEM 1: NORMALIZATION PROBLEM**
In this problem, create a random 5 x 5 ndarray and store it to variable X. Normalize X. Save your normalized 
ndarray as *X_normalized.nyp*

In [1]:
import numpy as np

In [3]:
# Create a randomized 5x5 ndarray
X = np.random.random((5,5))

# Normalize X using the mean and standard deviation
X_mean = X.mean()
X_std = X.std()
X_normalized = (X-X_mean)/X_std

# Saves the normalized ndarray as X_normalized.npy
np.save('X_normalized.npy', X_normalized)

# Prints the original and normalized arrays
print("Original Array:\n", X, "\n") ; print("Normalized Array: \n", X_normalized)

Original Array:
 [[0.56683661 0.21582953 0.64103044 0.72871331 0.43915539]
 [0.11175598 0.08952791 0.55263311 0.96455542 0.95184726]
 [0.56207245 0.64175039 0.97059601 0.32107184 0.79965017]
 [0.1669734  0.6881613  0.49911502 0.18341069 0.40578512]
 [0.4328592  0.24545125 0.68834724 0.74683721 0.63606509]] 

Normalized Array: 
 [[ 0.14178196 -1.2092698   0.42735942  0.76485716 -0.34967235]
 [-1.60985644 -1.69541392  0.08711166  1.67263057  1.62371592]
 [ 0.12344435  0.43013055  1.69588122 -0.80418448  1.03789828]
 [-1.39732058  0.60876952 -0.11888337 -1.33405226 -0.47811692]
 [-0.37390684 -1.09525363  0.6094852   0.83461735  0.40824743]]


### **PROBLEM 2: DIVISIBLE BY 3 PROBLEM**
Create the following 10 x 10 ndarray which are the squares of the first 100 positive integers. From this ndarray, determine all the elements that are divisible by 3. Save the result as *div_by_3.npy*.

In [5]:
# Create an array of the first 100 positive integers
A = np.arange(1,101)

# Compute squares of the elements and reshape the array into a 10x10 ndarray
A_squared = (np.square(A)).reshape(10,10)

# Determine all elements in A_squared that are divisible by 3
div_by_3 = A_squared[A_squared%3==0]

np.save('div_by_3', div_by_3)

print("Original 10X10 matrix with squared values:\n", A_squared); print("\nNumbers divisible by 3\n", div_by_3)

Original 10X10 matrix with squared values:
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

Numbers divisible by 3
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
